### PR TITLE
Clean up?

### PR DESCRIPTION
**Pull request by Maselko**
The functionality of the code is kept the same. I have added spaces after some arguments to improve readability(PEP-8 but not complete as it was a bit too far). Also, hanged the files in 'src' directory, so each file contains all the functions defined in the notebook with the same name.

I will have a more detailed look some time later.

### CODE REVIEW

**Comment by weymouth** [comment]
This means people would have to import both src files to get the full functionality. Why would that be a good change?

**Comment by Maselko** [comment]
The src is only two files. Just changed so the function 'wave_source' is moved 'geometries and plots', and changed names to the same notebook names.

**Comment by weymouth** [comment]
So this would help keep students from having functions presented out of order? 
Have you tested that the dependencies all work when importing both?
You have a number of repeated functions in the second src file. Can you remove those?

**Comment by Maselko** [comment]
Will do and pull back.

**Comment by weymouth** [comment]
I thought this was a good idea (and let me clean up the second notebook) so I took a pass at it this afternoon. I'm sure there are plenty of typos and other things, but I checked that the code runs for these cases and for the assignment.

**Pull request closed without merging**
